
import {PostProvider} from "@/context/index"
import { Lato } from "next/font/google";
import "./globals.css";

const inter = Lato({weight: ["300","400","700","900"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}){
  return (
    <html lang="en">
      <body >
        <PostProvider>
          <div>
            {children}
          </div>
        </PostProvider>
      </body>
    </html>
  )
}
